-- Creates the decks table in Supabase
CREATE TABLE "Decks" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Creates the Flashcards table in Supabase
CREATE TABLE "Flashcards" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    deck_id UUID REFERENCES "Decks"(id) ON DELETE CASCADE
);

-- Creates the Users table to store XP, level, and streak data
CREATE TABLE "Users" (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    xp INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    streak INTEGER DEFAULT 0,
    last_login TEXT,
    role TEXT DEFAULT 'student',
    PRIMARY KEY (id)
);

-- Creates the Classrooms table for teacher-created classrooms
CREATE TABLE "Classrooms" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    join_slug TEXT NOT NULL UNIQUE
);

-- Creates the Rosters table to track which students are in which classroom
CREATE TABLE "Rosters" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    classroom_id UUID REFERENCES "Classrooms"(id) ON DELETE CASCADE,
    student_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    UNIQUE(classroom_id, student_id)
);

-- Creates the Assignments table to track which decks are assigned globally
CREATE TABLE "Assignments" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    deck_id UUID REFERENCES "Decks"(id) ON DELETE CASCADE
);