-- Creates the decks table in Supabase
CREATE TABLE "Decks" (
                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                         title TEXT NOT NULL
);

-- Creates the Flashcards table in Supabase
CREATE TABLE "Flashcards" (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              front TEXT NOT NULL,
                              back TEXT NOT NULL,
                              deck_id UUID REFERENCES "Decks"(id) ON DELETE CASCADE
);

-- Creates the Users table to store XP, level, and streak data
CREATE TABLE "Users" (
                        id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
                        username TEXT NOT NULL UNIQUE,
                        xp INTEGER DEFAULT 0,
                        level INTEGER DEFAULT 1,
                        streak INTEGER DEFAULT 0,
                        PRIMARY KEY (id)
);