-- Creates the decks table in Supabase
CREATE TABLE "Decks" (
                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                         title TEXT NOT NULL
);

-- Creates the Flashcards table in Supabase
CREATE TABLE "Flashcards" (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              front TEXT NOT NULL,
                              back TEXT NOT NULL,
                              deck_id UUID REFERENCES "Decks"(id) ON DELETE CASCADE
);
